//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WR.Client.Resoures {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WrResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WrResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WR.Client.Resoures.WrResource", typeof(WrResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Server is not registered, please contact the administrator 的本地化字符串。
        /// </summary>
        public static string const_msg001_en {
            get {
                return ResourceManager.GetString("const_msg001_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器没有注册，请联系管理员 的本地化字符串。
        /// </summary>
        public static string const_msg001_zh {
            get {
                return ResourceManager.GetString("const_msg001_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No license server system for this feature 的本地化字符串。
        /// </summary>
        public static string const_msg002_en {
            get {
                return ResourceManager.GetString("const_msg002_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器没有得到许可 的本地化字符串。
        /// </summary>
        public static string const_msg002_zh {
            get {
                return ResourceManager.GetString("const_msg002_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No license server system for this feature 的本地化字符串。
        /// </summary>
        public static string const_msg003_en {
            get {
                return ResourceManager.GetString("const_msg003_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器没有得到许可 的本地化字符串。
        /// </summary>
        public static string const_msg003_zh {
            get {
                return ResourceManager.GetString("const_msg003_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The license to use this application has expired 的本地化字符串。
        /// </summary>
        public static string const_msg004_en {
            get {
                return ResourceManager.GetString("const_msg004_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器许可已经过期 的本地化字符串。
        /// </summary>
        public static string const_msg004_zh {
            get {
                return ResourceManager.GetString("const_msg004_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input your user id 的本地化字符串。
        /// </summary>
        public static string frm_login_msg001_en {
            get {
                return ResourceManager.GetString("frm_login_msg001_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入你的用户名 的本地化字符串。
        /// </summary>
        public static string frm_login_msg001_zh {
            get {
                return ResourceManager.GetString("frm_login_msg001_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input your password 的本地化字符串。
        /// </summary>
        public static string frm_login_msg002_en {
            get {
                return ResourceManager.GetString("frm_login_msg002_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入你的密码 的本地化字符串。
        /// </summary>
        public static string frm_login_msg002_zh {
            get {
                return ResourceManager.GetString("frm_login_msg002_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User id or password is invaild 的本地化字符串。
        /// </summary>
        public static string frm_login_msg003_en {
            get {
                return ResourceManager.GetString("frm_login_msg003_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或密码错误 的本地化字符串。
        /// </summary>
        public static string frm_login_msg003_zh {
            get {
                return ResourceManager.GetString("frm_login_msg003_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to quit the system? 的本地化字符串。
        /// </summary>
        public static string frm_main_msg001_en {
            get {
                return ResourceManager.GetString("frm_main_msg001_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要退出系统吗？ 的本地化字符串。
        /// </summary>
        public static string frm_main_msg001_zh {
            get {
                return ResourceManager.GetString("frm_main_msg001_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to finish the review? 的本地化字符串。
        /// </summary>
        public static string frm_preview_msg001_en {
            get {
                return ResourceManager.GetString("frm_preview_msg001_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要完成这个检查吗？ 的本地化字符串。
        /// </summary>
        public static string frm_preview_msg001_zh {
            get {
                return ResourceManager.GetString("frm_preview_msg001_zh", resourceCulture);
            }
        }
    }
}
